---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install required packages
  apt:
    name:
      - git
      - openjdk-17-jdk
      - docker.io
      - ansible
      - nodejs
      - npm
    state: present

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Add Jenkins repository key
  shell: >
    curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key |
    tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null

- name: Add Jenkins repository
  shell: >
    echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/" |
    tee /etc/apt/sources.list.d/jenkins.list > /dev/null

- name: Update apt cache after adding Jenkins repository
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Enable and start Jenkins service
  systemd:
    name: jenkins
    enabled: yes
    state: started

- name: Add Jenkins user to Docker group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Restart Jenkins
  systemd:
    name: jenkins
    state: restarted

- name: Ensure sudoers file has no-password access for ubuntu and jenkins
  lineinfile:
    path: /etc/sudoers
    line: "{{ item }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
  loop:
    - ubuntu
    - jenkins
