---
- name: Install required packages
  apt:
    name:
      - postfix
      - mailutils
    state: present
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Ensure Postfix configuration directory exists
  file:
    path: /etc/postfix
    state: directory
    mode: '0755'

- name: Create Postfix main configuration template
  template:
    src: postfix_main.cf.j2
    dest: /etc/postfix/main.cf

- name: Configure SMTP authentication
  copy:
    dest: /etc/postfix/sasl_passwd
    content: |
      [smtp.gmail.com]:587 {{ smtp_email }}:{{ smtp_password }}
    mode: '0600'

- name: Secure and Compile Authentication File
  command: postmap /etc/postfix/sasl_passwd

- name: Restart Postfix
  systemd:
    name: postfix
    state: restarted

- name: Open SMTP port in UFW
  ufw:
    rule: allow
    port: 587
    proto: tcp
